image: node:10.16.3

# This folder is cached between builds
# http://docs.gitlab.com/ee/ci/yaml/README.html#cache

stages:
    - build
    - deploy

build:
    stage: 'build'
    script:
        - npm install
        - npm ci
        - npm run build
    cache:
        paths:
            - node_modules/
    only:
        - development
        - master