export const drinkLevels = [
  'userManagement.drinklevel.none',
  'userManagement.drinklevel.novice',
  'userManagement.drinklevel.average',
  'userManagement.drinklevel.aboveaverage',
  'userManagement.drinklevel.good',
  'userManagement.drinklevel.expert',
];
export const studyLevels = [
  'userManagement.studyLevel.highschool',
  'userManagement.studyLevel.college',
  'userManagement.studyLevel.university',
  'userManagement.studyLevel.master',
];
// 0: ENGLISH, 1:Japanese, 2: Korean, 3: Chinese
export const languages = [
  'userManagement.languages.english',
  'userManagement.languages.japanese',
  'userManagement.languages.korean',
  'userManagement.languages.chinese',
];

export const cities = [
  { code: 'SG', name: 'Hồ Chí Minh' },
  { code: 'HN', name: 'Hà Nội' },
  { code: 'DDN', name: 'Đà Nẵng' },
  { code: 'BD', name: 'Bình Dương' },
  { code: 'DNA', name: 'Đồng Nai' },
  { code: 'KH', name: 'Khánh Hòa' },
  { code: 'HP', name: 'Hải Phòng' },
  { code: 'LA', name: 'Long An' },
  { code: 'QNA', name: 'Quảng Nam' },
  { code: 'VT', name: 'Bà Rịa Vũng Tàu' },
  { code: 'DDL', name: 'Đắk Lắk' },
  { code: 'CT', name: 'Cần Thơ' },
  { code: 'BTH', name: 'Bình Thuận  ' },
  { code: 'LDD', name: 'Lâm Đồng' },
  { code: 'TTH', name: 'Thừa Thiên Huế' },
  { code: 'KG', name: 'Kiên Giang' },
  { code: 'BN', name: 'Bắc Ninh' },
  { code: 'QNI', name: 'Quảng Ninh' },
  { code: 'TH', name: 'Thanh Hóa' },
  { code: 'NA', name: 'Nghệ An' },
  { code: 'HD', name: 'Hải Dương' },
  { code: 'GL', name: 'Gia Lai' },
  { code: 'BP', name: 'Bình Phước' },
  { code: 'HY', name: 'Hưng Yên' },
  { code: 'BDD', name: 'Bình Định' },
  { code: 'TG', name: 'Tiền Giang' },
  { code: 'TB', name: 'Thái Bình' },
  { code: 'BG', name: 'Bắc Giang' },
  { code: 'HB', name: 'Hòa Bình' },
  { code: 'AG', name: 'An Giang' },
  { code: 'VP', name: 'Vĩnh Phúc' },
  { code: 'TNI', name: 'Tây Ninh' },
  { code: 'TN', name: 'Thái Nguyên' },
  { code: 'LCA', name: 'Lào Cai' },
  { code: 'NDD', name: 'Nam Định' },
  { code: 'QNG', name: 'Quảng Ngãi' },
  { code: 'BTR', name: 'Bến Tre' },
  { code: 'DNO', name: 'Đắk Nông' },
  { code: 'CM', name: 'Cà Mau' },
  { code: 'VL', name: 'Vĩnh Long' },
  { code: 'NB', name: 'Ninh Bình' },
  { code: 'PT', name: 'Phú Thọ' },
  { code: 'NT', name: 'Ninh Thuận' },
  { code: 'PY', name: 'Phú Yên' },
  { code: 'HNA', name: 'Hà Nam' },
  { code: 'HT', name: 'Hà Tĩnh' },
  { code: 'DDT', name: 'Đồng Tháp' },
  { code: 'ST', name: 'Sóc Trăng' },
  { code: 'KT', name: 'Kon Tum' },
  { code: 'QB', name: 'Quảng Bình' },
  { code: 'QT', name: 'Quảng Trị' },
  { code: 'TV', name: 'Trà Vinh' },
  { code: 'HGI', name: 'Hậu Giang' },
  { code: 'SL', name: 'Sơn La' },
  { code: 'BL', name: 'Bạc Liêu' },
  { code: 'YB', name: 'Yên Bái' },
  { code: 'TQ', name: 'Tuyên Quang' },
  { code: 'DDB', name: 'Điện Biên' },
  { code: 'LCH', name: 'Lai Châu' },
  { code: 'LS', name: 'Lạng Sơn' },
  { code: 'HG', name: 'Hà Giang' },
  { code: 'BK', name: 'Bắc Kạn' },
  { code: 'CB', name: 'Cao Bằng' },
];
